# Generated by Django 2.1.4 on 2020-08-12 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 19, 9, 14, 292739), verbose_name='date published'),
        ),
    ]
